### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by willpearse** [pearselab/r-intro-AlexRego#1]
We haven't really spoken much Alex, but if you want to talk about aspects of the course please come by my table and say hello. I notice you're a little behind on the first exercise, and have focused quite a lot on exercise 2. Would you like help with the other exercises?

**Comment by AlexRego** [comment]
I'm enrolled in a separate Python course that's gobbling up quite a bit of my time, so I haven't spent as much time as I would like on these exercises. I'm confident that I will be on track by Friday though. I will be sure to visit your table or request an appointment if I need any help. Thank you!

**Comment by willpearse** [comment]
OK. Just be aware that it's very easy to fall behind, and programming problems don't tend to lend themselves well to last-minute attempts at exercises...
